/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CircularLinkedList;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        CircularLinkedList cll = new CircularLinkedList();
        Random rand = new Random();

        cll.display();

        System.out.println("Inserting 10 items");
        for(int i = 0; i < 10; i++) {
            cll.insert(rand.nextInt(100));
        }

        System.out.println();
        cll.display();
        System.out.println();

        System.out.println("Deleted: " + cll.delete());
        System.out.println("Deleted: " + cll.delete());
        System.out.println("Deleted: " + cll.delete());

        cll.step();
        cll.step();
        cll.step();

        System.out.println("Stepped 3 times");
        System.out.println();
        cll.display();
        System.out.println();

        cll.insert(-50);
        System.out.println("Inserted '-50'");

        System.out.println();
        cll.display();
        System.out.println();

        System.out.println("Searched for '-50' got " + cll.search(-50));
        System.out.println("Searched for '-20' got " + cll.search(-20));
        System.out.println();

        while(!cll.isEmpty()) {
            System.out.println("Deleted: " + cll.delete());
        }

        cll.display();
    }
}
