/*
 * This source file was generated by the Gradle 'init' task
 */
package TwoThreeFour;
import java.util.Random;

public class App {

    public static void main(String[] args) {
        Tree234 t = new Tree234();
        t.insert(40);
        t.insert(20);
        t.insert(50);
        t.insert(25);
        t.insert(4);
        t.insert(43);
        t.insert(41);
        t.insert(21);
        t.insert(51);
        t.insert(26);
        t.insert(5);
        t.insert(44);

        Random rand = new Random();

        // for(int i = 0; i < 100; i++) {
        //     t.insert(rand.nextInt(-101, 101));
        // }

        //Delete method marks the node containing the key as
        System.out.println("Tree after inserting (using inorder traversal): ");
        t.inorderTraversal();


        System.out.println("\nDeleting 43");
        t.delete(43);

        System.out.println("Tree after deletion:");
        t.inorderTraversal();


        System.out.println("\nSearching for 44 (-1 if not found):");
        System.out.println(t.search(44));

        System.out.println("\nSearching for -3 (-1 if not found):");
        System.out.println(t.search(-3));
    }
}
