/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lists;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Random;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;

class AppTest {

}
