/*
 * This source file was generated by the Gradle 'init' task
 */
package ExtraCredit;

public class App {

    public static void main(String[] args) {

        ExtraCredit ec = new ExtraCredit();

        ec.decimalToBinary();
    }
}
